* T.H.W.A.P. Emacs Configuration

I recently advised someone against rolling their own emacs configuration. Then I did it, because I'm smart like that.
As it turns out, yeah, I was wrong. The result of rolling my own is a nice fast distribution that is somewhat opinionated.

** Installation

Simply clone this repository as your ~/.emacs.d directory and start emacs.

#+BEGIN_SRC
$ test -d ~/.emacs.d && mv ~/.emacs.d ~/emacs.d ; git clone https://github.com/fuzzy/thwapmacs ~/.emacs.d
$ emacs
#+END_SRC

This configuration bootstraps and uses straight.el to manage all package installations.

** Help

All keybindings set in this configuration are listed on the dashboard. Any other keybindings set by this configuration
were the recommended defaults from the package. If a non-default was chosen, it is listed in the help information on
the dashboard.

Additionally, with any custom configuration you may do, if you wish your keybindings to be added to the *thwap-map*,
you may do so with the provided *thwap/add-key-binding* function, like so:

#+begin_src emacs-lisp
(thwap/add-key-binding "M-s" 'org-edit-special "Edit the source at this point, in it's native mode")
#+end_src

This will prefix it with *C-c t* like all other T.H.W.A.P. Emacs commands, but it will also place the help message
into the dashboard's greeting message as a reminder.
